#include "main.h"

volatile uint32_t tick = 0;
uint32_t led1Tick = 0;
uint32_t led2Tick = 0;
uint32_t led3Tick = 0;

int main(void)
{
	//Enabling the clock A pin
	RCC->AHB1ENR |= (1 << 0);

	//Setting the PIN PA4, PA5, PA6 as output led pin

	GPIOA->MODER &= ~(3 << (4 * 2));
	GPIOA->MODER |=  (1 << (4 * 2));

	GPIOA->MODER &= ~(3 << (5 * 2));
	GPIOA->MODER |=  (1 << (5 * 2));

	GPIOA->MODER &= ~(3 << (6 * 2));
	GPIOA->MODER |=  (1 << (6 * 2));

	// Configuring the timer

	RCC->APB1ENR |= (1 << 0);

	TIM2->PSC = 1599;
	TIM2->ARR = 9;

	// Generate an update event to load PSC and ARR
	TIM2->EGR |= (1 << 0);

	// Clear the update interrupt flag generated by EGR
	TIM2->SR &= ~(1 << 0);

	// Enable Update Interrupt
	TIM2->DIER |= (1 << 0);

	// Enable TIM2 Interrupt in NVIC
	NVIC_EnableIRQ(TIM2_IRQn);

	// Start Timer
	TIM2->CR1 |= (1 << 0);


	while(1)
	{
	    // Task 1 (200 ms)
	    if((tick - led1Tick) >= 200)
	    {
	        led1Tick = tick;
	        GPIOA->ODR ^= (1 << 4);
	    }

	    // Task 2 (500 ms)
	    if((tick - led2Tick) >= 500)
	    {
	        led2Tick = tick;
	        GPIOA->ODR ^= (1 << 5);
	    }

	    // Task 3 (1000 ms)
	    if((tick - led3Tick) >= 1000)
	    {
	        led3Tick = tick;
	        GPIOA->ODR ^= (1 << 6);
	    }
	}

}

void TIM2_IRQHandler(void)
{
	//Check if Update Interrupt occurred
	if(TIM2->SR & (1 << 0))
	{
		//Clear Update Interrupt Flag
		TIM2->SR &= ~(1 << 0);

		//Increment system tick
		tick++;
	}
}
